like_publication:
    path: /like/{id}
    defaults: { _controller: AppBundle:Like:like, id:null }
    
unlike_publication:
    path: /unlike/{id}
    defaults: { _controller: AppBundle:Like:unlike, id:null }
    
user_likes:
    path: /likes/{nickname}
    defaults: { _controller: AppBundle:Like:likes, nickname:null }
