notifications_page:
    path: /notifications
    defaults: { _controller: AppBundle:Notification:index }
    
notifications_ajax:
    path: /notifications/get
    defaults: { _controller: AppBundle:Notification:countNotifications }
    
